kafka:

  kafka-container:
    bootstrap-servers: kafka:29092

routes:

  # copy the sales topic from winterthur to switzerland
  sales-winterthur-switzerland:
    source: kafka-container
    source-topic: sales-winterthur
    target: kafka-container
    target-topic: sales-switzerland

  # copy the sales topic from chur to switzerland
  sales-chur-switzerland:
    source: kafka-container
    source-topic: sales-chur
    target: kafka-container
    target-topic: sales-switzerland
